### ISSUE TITLE
build-essential (i.e. "make") no longer in upstream

### ISSUE THREAD

**Issue by baschny** [webdevops/samson-deployment#30]
I pulled latest images from samson-deployment and build our deployment server again, and it turns out that the "make" is no longer available. 

I've added to our Dockerfile:

```
RUN set -ex ; apt-get update ; apt-get install -y build-essential
```

Which fixes the problem. But I guess this is something that could / should be done upstream.

**Comment by mblaschke** [comment]
Fixed with Dockerfile release 1.2.1
